package com.ubiquity.sprocket.api.interceptors;

public interface ErrorKeys {
	String AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
	String USER_NOT_EXIST = "USER_NOT_EXIST";
	String ORDER_NOT_EXIST = "ORDER_NOT_EXIST";
	String ITEM_NOT_EXIST = "ITEM_NOT_EXIST";
	String CONTACT_NOT_EXIST ="CONTACT_NOT_EXIST";
	String Account_DENIED = "Account_DENIED";
	String INVALID_PROVIDER = "INVALID_PROVIDER";
	
	String ORDER_NOT_VALID = "ORDER_NOT_VALID";
	String CONTACT_NOT_VALID = "CONTACT_NOT_VALID";
	String REDEEM_DENIED = "REDEEM_DENIED";
	String REDEEM_ERROR = "REDEEM_ERROR";
	String EXCHANGE_DENIED = "EXCHANGE_DENIED";
	String EXCHANGE_DENIED2 = "EXCHANGE_DENIED2";
	String ALREADY_REDEEMED = "ALREADY_REDEEMED";
	String ALREADY_EXCHANGED = "ALREADY_EXCHANGED";
	String INVALID_VALUE = "INVALID_VALUE";
	
}
