-- Script generated by MySQL Compare 1.0.0.425 on 2/23/2015 12:50:05 AM

SET @ORIGINAL_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @ORIGINAL_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @ORIGINAL_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES,NO_AUTO_VALUE_ON_ZERO,NO_AUTO_CREATE_USER';

USE `sprocket`;

ALTER TABLE `sprocket`.`place`
  MODIFY COLUMN `external_network` int(11) NOT NULL DEFAULT '-1';

ALTER TABLE `sprocket`.`user`
  ADD COLUMN `canPurchase` bit(1) NULL 
  , ADD COLUMN `canRedeem` bit(1) NULL;


/*ALTER TABLE `sprocket`.`activity`
  MODIFY COLUMN `title` varchar(300) NULL;*/

ALTER TABLE `sprocket`.`activity_interests` DROP FOREIGN KEY `FK_jd3leq7qqeqldsp31n1op3ets`;

ALTER TABLE `sprocket`.`activity_interests` ADD FOREIGN KEY (`activity_id`) REFERENCES `sprocket`.`activity` (`activity_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `sprocket`.`external_identity`
  MODIFY COLUMN `external_network` int(11) NOT NULL DEFAULT '-1'
  , ADD COLUMN `created_at` bigint(20) NULL;

ALTER TABLE `sprocket`.`native_identity`
  MODIFY COLUMN `username` varchar(255) NOT NULL;

ALTER TABLE `sprocket`.`native_identity` ADD UNIQUE KEY `username`(`username`);

/*ALTER TABLE `sprocket`.`native_identity` ADD UNIQUE KEY `username_2`(`username`);*/

ALTER TABLE `sprocket`.`video_content`
  MODIFY COLUMN `external_network` int(11) NOT NULL DEFAULT '-1';

CREATE TABLE `sprocket`.`admin` (
  `admin_id` bigint(20) NOT NULL auto_increment,
  `client_platform` int(11) NOT NULL,
  `display_name` varchar(100) NULL,
  `email` varchar(100) NULL,
  `is_active` bit(1) NOT NULL,
  `is_verified` bit(1) NULL,
  `last_login` bigint(20) NOT NULL,
  `last_updated` bigint(20) NOT NULL,
  `password` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE KEY `UK_c0r9atamxvbhjjvy5j8da1kam`(`email`),
  UNIQUE KEY `UK_gfn44sntic2k93auag97juyij`(`username`)
) ENGINE=InnoDB;

CREATE TABLE `sprocket`.`developer` (
  `developer_id` bigint(20) NOT NULL auto_increment,
  `display_name` varchar(100) NULL,
  `email` varchar(100) NULL,
  `first_name` varchar(100) NULL,
  `is_active` bit(1) NOT NULL,
  `last_name` varchar(100) NULL,
  `last_updated` bigint(20) NOT NULL,
  `password` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  PRIMARY KEY (`developer_id`),
  UNIQUE KEY `UK_7he3e2kpo85x20u5oefpkddt8`(`username`),
  UNIQUE KEY `UK_chmq1wdfnhjthxo65affwdnky`(`email`)
) ENGINE=InnoDB;

CREATE TABLE `sprocket`.`application` (
  `app_id` bigint(20) NOT NULL auto_increment,
  `app_key` varchar(255) NOT NULL,
  `app_secret` varchar(255) NOT NULL,
  `created_at` bigint(20) NOT NULL,
  `description` longtext NOT NULL,
  `is_active` bit(1) NOT NULL,
  `last_updated` bigint(20) NOT NULL,
  `name` varchar(255) NOT NULL,
  `owner_id` bigint(20) NOT NULL,
  PRIMARY KEY (`app_id`),
  UNIQUE KEY `UK_bdsj16iyf8tgetnqcxu0rh4yb`(`app_key`),
  UNIQUE KEY `UK_otei7qlrfq3pfjtcdwfwjeskp`(`app_secret`),
  FOREIGN KEY (`owner_id`) REFERENCES `sprocket`.`developer` (`developer_id`),
  KEY `FK_hmxyq9oplk2w6au8uo9vs6qtw`(`owner_id`)
) ENGINE=InnoDB;

CREATE TABLE `sprocket`.`external_network_application` (
  `ex_app_id` bigint(20) NOT NULL auto_increment,
  `api_key` varchar(255) NULL,
  `client_platform` int(11) NOT NULL,
  `consumer_key` varchar(255) NOT NULL,
  `consumer_secret` varchar(255) NOT NULL,
  `external_network` int(11) NOT NULL,
  `redirect_url` varchar(255) NULL,
  `token` varchar(255) NULL,
  `token_secret` varchar(255) NULL,
  `user_agent` varchar(255) NULL,
  `app_id` bigint(20) NOT NULL,
  PRIMARY KEY (`ex_app_id`),
  FOREIGN KEY (`app_id`) REFERENCES `sprocket`.`application` (`app_id`),
  KEY `FK_gtmub0ryegmrcq0m82mvs7fs9`(`app_id`)
) ENGINE=InnoDB;

CREATE TABLE `sprocket`.`sec_role` (
  `role_id` bigint(20) NOT NULL auto_increment,
  `name` varchar(15) NOT NULL,
  UNIQUE KEY `name`(`name`),
  PRIMARY KEY (`role_id`)
) ENGINE=InnoDB;

CREATE TABLE `sprocket`.`sec_admin_role` (
  `admin_id` bigint(20) NOT NULL,
  `role_id` bigint(20) NOT NULL,
  PRIMARY KEY (`admin_id`,`role_id`),
  FOREIGN KEY (`admin_id`) REFERENCES `sprocket`.`admin` (`admin_id`),
  FOREIGN KEY (`role_id`) REFERENCES `sprocket`.`sec_role` (`role_id`),
  KEY `FK_os7jvh2e7loj940ijopj9ycb0`(`role_id`)
) ENGINE=InnoDB;

CREATE TABLE `sprocket`.`user_contact` (
  `user_contact_id` bigint(20) NOT NULL auto_increment,
  `created_at` bigint(20) NOT NULL,
  `external_network` int(11) NOT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `last_updated` bigint(20) NOT NULL,
  `contact_id` bigint(20) NULL,
  `user_id` bigint(20) NULL,
  PRIMARY KEY (`user_contact_id`),
  FOREIGN KEY (`user_id`) REFERENCES `sprocket`.`user` (`user_id`),
  FOREIGN KEY (`contact_id`) REFERENCES `sprocket`.`contact` (`contact_id`),
  KEY `FK_gf3ye20ssuitmwm25hveokk1b`(`user_id`),
  KEY `FK_qt05uxtkdoic3mao76g30sn90`(`contact_id`)
) ENGINE=InnoDB;

ALTER TABLE `sprocket`.`activity_interests` ADD FOREIGN KEY (`activity_id`) REFERENCES `sprocket`.`activity` (`activity_id`) ON DELETE CASCADE ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS=@ORIGINAL_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@ORIGINAL_UNIQUE_CHECKS;
SET SQL_MODE=@ORIGINAL_SQL_MODE;


/*-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

USE sprocket;
ALTER TABLE contact Drop FOREIGN KEY FK_cmaoslcxl4a8rr6co6epf8nkj;
ALTER TABLE contact Drop COLUMN owner_id ;

#already updated
#ALTER TABLE contact Drop COLUMN is_deleted ;
#ALTER TABLE activity MODIFY COLUMN external_identifier varchar(255) not null;
#ALTER TABLE activity MODIFY COLUMN creation_date bigint(20) not null;

Update user set canPurchase=0 ,canRedeem =0 ;

#insert record for each contact of external identity in user_contact
insert into user_contact (contact_id, user_id, is_deleted, external_network, created_at, last_updated)  from
select c.contact_id, identity.user_id, 0, i.external_network, identity.last_updated, identity.last_updated from contact c inner join external_identity i on c.external_identity = i.identity_id 
                          inner join identity on i.identity_id = identity.identity_id 
                          where identity.user_id is not null;


