USE sprocket;
delete from external_network_application_platforms;
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (1,2);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (1,0);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (1,1);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (2,1);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (3,2);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (4,2);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (4,0);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (4,1);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (5,2);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (5,0);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (5,1);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (6,0);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (6,1);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (7,2);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (8,2);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (8,0);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (8,1);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (9,0);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (9,1);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (10,2);
insert into `external_network_application_platforms`(`ex_app_id`,`client_platform`) values (11,0);
